### PR TITLE
removes nesting from recorded events

### LINKED ISSUE #202: Remove nesting from $recordedEvents
The current implementation for transactions stores all events from an aggregate in an $recordedEvents object. On every call to ```EventStore::create``` or ```EventStore::appendTo``` this object will be nested in itself.

@mikemix has provided an example where this could trigger xdebugs max nesting function level exception.
https://gist.github.com/mikemix/5ebb1726c42aeea633eca1feec1120e3

Maybe there is a better way to store this events, without an infinite nesting, which could have also positiv impact on performance.

I would suggest $recordedEvents is always an AppendIterator and got new events appended, instead of be nested on every round.

/cc @prolic

### PR DESCRIPTION
**Pull request by oqq**
This PR closes #202

### CODE REVIEW

**Comment by prolic** [comment]
Can you add a test-case that is failing without this?

**Comment by codeliner** [comment]
@prolic I guess a test-case is difficult here because the test would need to reach xdebugs max nesting function level and therefor xdebug would need to be installed and set up with an appropriate limit.

File: src/EventStore.php [hunk 1]
```diff
@@ -359,7 +350,7 @@ public function rollback(): void
 
         $this->actionEventEmitter->dispatch($event);
 
-        $this->recordedEvents = new ArrayIterator();
+        $this->resetRecordedEvents();
```
Comment (sandrokeil) [inline src/EventStore.php]: I'm not sure if it is worth it, to create a new method for a one line of code? I would prefer `$this->recorderEvents = new AppendIterator()`. Every function call in PHP is a performance drawback too.

Comment (prolic) [inline src/EventStore.php]: :+1:

Comment (codeliner) [inline src/EventStore.php]: @oqq In a domain model I would do it exactly like you: clean and readable code that tells you what it does. But @sandrokeil 's reasoning wins here, because prooph is infrastructure and performance has very high priority.

Comment (oqq) [inline src/EventStore.php]: Of course, my reason was to be consistent what "recordedEvents" should be. But i agree with the performance reasons.

**Comment by oqq** [comment]
It would be possible to implement a hackish test case, which would be skipped if xdebug is not available. But for me it is currently not possible to run xdebug with php7.1

**Comment by prolic** [comment]
also manually merged into master

**Comment by prolic** [comment]
see: https://github.com/prooph/event-store/releases/tag/v6.5.1
